"""Business case model for the My Health Data Locker pilot.

Every input is an explicit, editable assumption. None of the defaults are
ZiffyHealth company data; they are conservative planning placeholders chosen
so the case does not depend on optimistic numbers. Replace them with pilot
baselines as soon as the 5–10 clinic pilot produces real figures.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, replace

import numpy as np
import pandas as pd


@dataclass
class Assumptions:
    clinics: int = 10                      # pilot e-clinics
    patients_per_clinic_month: int = 300   # unique patients / clinic / month
    repeat_rate_base: float = 0.30         # share returning within 90 days (baseline)
    repeat_uplift_pp: float = 0.03         # +3 percentage points from Locker
    revenue_per_visit: float = 350.0       # ₹ blended consult + diagnostics + pharmacy margin
    visits_per_returning_patient: float = 1.5  # visits generated by each retained patient
    contribution_margin: float = 0.35      # share of revenue that is contribution
    status_calls_per_patient: float = 0.8  # "where is my report?" style calls
    call_deflection: float = 0.35          # share of those calls avoided
    cost_per_call: float = 40.0            # ₹ fully loaded operator / support time
    messages_per_patient: float = 6.0      # Care Moments per journey
    cost_per_message: float = 0.15         # ₹ per WhatsApp utility message (check current Meta rate)
    build_cost: float = 1_200_000.0        # ₹ one-time: integration, hardening, testing
    compliance_setup: float = 300_000.0    # ₹ one-time: DPO review, DPIA, policies
    run_cost_month: float = 20_000.0       # ₹ fixed: hosting, monitoring, security tooling
    run_cost_per_clinic: float = 1_500.0   # ₹ per clinic per month: support, operator refreshers
    onboarding_per_new_clinic: float = 15_000.0  # ₹ one-time per clinic added at scale
    ramp_months: int = 3                   # months to reach full effect
    discount_rate_annual: float = 0.14     # hurdle rate for an early-stage health-tech
    months: int = 36
    scale_clinics_after_12m: int = 40      # extra clinics added from month 13 (0 = pilot only)


LABELS = {
    "repeat_uplift_pp": "Repeat-visit uplift",
    "revenue_per_visit": "Revenue per visit",
    "contribution_margin": "Contribution margin",
    "call_deflection": "Call deflection",
    "cost_per_call": "Cost per call",
    "build_cost": "Build cost",
    "run_cost_month": "Fixed monthly run cost",
    "patients_per_clinic_month": "Patients per clinic",
}


def monthly_cashflows(a: Assumptions) -> pd.DataFrame:
    rows = []
    for m in range(1, a.months + 1):
        clinics = a.clinics + (a.scale_clinics_after_12m if m > 12 else 0)
        ramp = min(1.0, m / max(a.ramp_months, 1))
        patients = clinics * a.patients_per_clinic_month
        extra_visits = patients * a.repeat_uplift_pp * ramp
        retention_gain = (extra_visits * a.visits_per_returning_patient
                          * a.revenue_per_visit * a.contribution_margin)
        support_saving = patients * a.status_calls_per_patient * a.call_deflection * ramp * a.cost_per_call
        messaging = patients * a.messages_per_patient * a.cost_per_message
        run = a.run_cost_month + a.run_cost_per_clinic * clinics
        one_time = (a.build_cost + a.compliance_setup) if m == 1 else 0.0
        if m == 13:
            one_time += a.onboarding_per_new_clinic * a.scale_clinics_after_12m
        net = retention_gain + support_saving - messaging - run - one_time
        rows.append({"month": m, "clinics": clinics, "patients": patients,
                     "retention_gain": retention_gain, "support_saving": support_saving,
                     "messaging_cost": -messaging, "run_cost": -run, "one_time": -one_time,
                     "net": net})
    df = pd.DataFrame(rows)
    df["cumulative"] = df["net"].cumsum()
    return df


def npv(a: Assumptions, df: pd.DataFrame | None = None) -> float:
    df = monthly_cashflows(a) if df is None else df
    r = (1 + a.discount_rate_annual) ** (1 / 12) - 1
    return float((df["net"] / (1 + r) ** df["month"]).sum())


def payback_month(df: pd.DataFrame) -> int | None:
    pos = df.index[df["cumulative"] >= 0]
    return int(df.loc[pos[0], "month"]) if len(pos) else None


def roi_multiple(df: pd.DataFrame) -> float:
    invest = -(df["one_time"].sum() + df["run_cost"].sum() + df["messaging_cost"].sum())
    gain = df["retention_gain"].sum() + df["support_saving"].sum()
    return float(gain / invest) if invest else float("nan")


def summary(a: Assumptions) -> dict:
    df = monthly_cashflows(a)
    return {"npv": npv(a, df), "payback": payback_month(df), "roi": roi_multiple(df),
            "total_gain": float(df["retention_gain"].sum() + df["support_saving"].sum()),
            "total_cost": float(-(df["one_time"].sum() + df["run_cost"].sum() + df["messaging_cost"].sum()))}


def tornado(a: Assumptions, swing: float = 0.25) -> pd.DataFrame:
    base = npv(a)
    rows = []
    for field, label in LABELS.items():
        v = getattr(a, field)
        lo = npv(replace(a, **{field: type(v)(v * (1 - swing))}))
        hi = npv(replace(a, **{field: type(v)(v * (1 + swing))}))
        rows.append({"driver": label, "low": lo - base, "high": hi - base,
                     "range": abs(hi - lo)})
    return pd.DataFrame(rows).sort_values("range")


def breakeven_uplift(a: Assumptions) -> float | None:
    """Smallest repeat-visit uplift (pp) giving NPV ≥ 0 over the horizon."""
    lo, hi = 0.0, 0.30
    if npv(replace(a, repeat_uplift_pp=hi)) < 0:
        return None
    for _ in range(40):
        mid = (lo + hi) / 2
        if npv(replace(a, repeat_uplift_pp=mid)) >= 0:
            hi = mid
        else:
            lo = mid
    return hi


def as_dict(a: Assumptions) -> dict:
    return asdict(a)


def monte_carlo(a: Assumptions, n: int = 2000, seed: int = 3) -> np.ndarray:
    """NPV distribution with triangular uncertainty on the uncertain drivers."""
    rng = np.random.default_rng(seed)
    out = np.empty(n)
    for i in range(n):
        s = replace(
            a,
            repeat_uplift_pp=float(rng.triangular(0.0, a.repeat_uplift_pp, a.repeat_uplift_pp * 2)),
            call_deflection=float(rng.triangular(a.call_deflection * 0.4, a.call_deflection, min(0.9, a.call_deflection * 1.5))),
            build_cost=float(rng.triangular(a.build_cost * 0.8, a.build_cost, a.build_cost * 1.8)),
            patients_per_clinic_month=int(rng.triangular(a.patients_per_clinic_month * 0.6,
                                                         a.patients_per_clinic_month,
                                                         a.patients_per_clinic_month * 1.3)),
        )
        out[i] = npv(s)
    return out
